# Generated by Django 4.0.2 on 2022-02-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('author', models.CharField(max_length=10)),
                ('publicationDate', models.TimeField()),
            ],
        ),
    ]
